apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terminal-admin-cluster-binding
subjects:
- kind: ServiceAccount
  name: terminal-admin
  namespace: student-terminals
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io