apiVersion: v1
kind: Secret
metadata:
  name: keycloak-oauth-secret
  namespace: student-terminals
type: Opaque
stringData:
  # Replace these values with your actual Keycloak configuration
  client-id: "your-client-id"
  client-secret: "your-client-secret"
  cookie-secret: "CHANGE-ME-TO-RANDOM-32-CHARS"  # Generate with: openssl rand -base64 32
